### PR TITLE
Fixes for Chef 15

### PR DESCRIPTION
**Pull request by EMH333**
The ohai_plugin resource from the dovecot cookbook fails idempotency checks currently so unfortunately had to disable them to converge. 

The fix suggested for only sending the test email once worked perfectly.

Also had to slightly adjust the SQL for the auth testing cookbook because it would insert duplicate rows which caused a problem when trying to login. Now the username row is unique and combined with the insert query ignoring duplicate row errors, we should be good to go.

### CODE REVIEW

**Comment by EMH333** [comment]
[Chef 15: osl-imap](https://trello.com/c/O5OEJBfp/1812-chef-15-osl-imap)

**Review by ramereth — APPROVED** [review]
Please do a minor bump on ``*`` envs

**Comment by EMH333** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.2.0.  Have a nice day!

**Pull request merged**
